// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Jg_WKp_jiNFvoAW6TkytTSa-EYcaNXY',
    appId: '1:448677397742:web:ee64de598895ecc2925fff',
    messagingSenderId: '448677397742',
    projectId: 'taskapp-eb0fd',
    authDomain: 'taskapp-eb0fd.firebaseapp.com',
    storageBucket: 'taskapp-eb0fd.appspot.com',
    measurementId: 'G-LW6Q0RBYPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLP7DWQ1r_gDy18Y4ovDQwYT4ntkWgkww',
    appId: '1:448677397742:android:3d4039b8f5f424b5925fff',
    messagingSenderId: '448677397742',
    projectId: 'taskapp-eb0fd',
    storageBucket: 'taskapp-eb0fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqLGPalhUcpt2p3l1O2Zz_huD0YHI-Yow',
    appId: '1:448677397742:ios:4d6c209debbd5eeb925fff',
    messagingSenderId: '448677397742',
    projectId: 'taskapp-eb0fd',
    storageBucket: 'taskapp-eb0fd.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqLGPalhUcpt2p3l1O2Zz_huD0YHI-Yow',
    appId: '1:448677397742:ios:4a1f324cb9f78261925fff',
    messagingSenderId: '448677397742',
    projectId: 'taskapp-eb0fd',
    storageBucket: 'taskapp-eb0fd.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
